### ISSUE TITLE
Error Messages and Static Analysis

### ISSUE THREAD

**Issue by Zamua** [JMU-CS/less-java#11]
Less-Java does not implement any kind of static analysis.

If a less-java program makes it through the front end of the compiler without error, then there is a chance that other semantic errors will be exposed when the generated java source is compiled. In this case, java displays error stack traces referencing objects and line numbers in the generated source. This makes debugging especially frustrating.

Solutions:

- Implement sufficient static analysis
- Parse the output and map the references back to the less-java source

**Comment by lam2mo** [comment]
Items from wiki:
  * duplicate symbols
  * return/break locations
  * expression types
  * function parameters
  * report line numbers
  * type unification failures

**Comment by lam2mo** [comment]
This (or at least a significant part of it) is now part of @hinescd's thesis.

**Comment by hinescd** [comment]
Currently all that's left for resolving this issue is static analysis for method calls (making sure they exist and are visible, etc.)

**Comment by lam2mo** [comment]
@hinescd is this resolved now?
