### ISSUE TITLE
Expose type unification intermediate results

### ISSUE THREAD

**Issue by lam2mo** [JMU-CS/less-java#22]
For debugging purposes, it would be useful to see the unification decisions during compilation. Adding a command-line option to enable this output would be optimal.

**Comment by lam2mo** [comment]
@hinescd Is this done? I seem to remember you added this already.

**Comment by hinescd** [comment]
I have it printing out some information if you pass the -t flag to compile.sh, but the output can be overwhelming for a program longer than just a few lines

**Comment by lam2mo** [comment]
Right, I thought so, and that's fine because it's really only for debugging the inference engine and so presumably the first step of tackling a bug in that part is to make a smallest reproducible example. I'm going to call this closed. Thanks!
