### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by lam2mo** [JMU-CS/less-java#30]

**Comment by lam2mo** [comment]
Fixed by 347a8b6c16e53ad3ca3dbf57e7bde61be18366e0.

**Comment by lam2mo** [comment]
I'm re-opening this issue because I think we need to clean up the README a bit, and take examples like these for guidance:

* https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
* https://github.com/jehna/readme-best-practices

**Comment by kylelaker** [comment]
#45 made significant attempts towards resolving this, but I am unsure whether the goals are completely satisfied

**Comment by lam2mo** [comment]
Thanks so much! It looks fine for now and adds everything I was thinking of so I'm going to close this issue now. We will need to clean up the README again after we make more progress toward #23.
