### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Zamua** [JMU-CS/less-java#33]
Perhaps related to #19 

Add some kind of CI tool to automatically run tests and help manage contributions

**Comment by hinescd** [comment]
Is this addressed by #34?

**Comment by Zamua** [comment]
No, I was thinking something more like Travis CI or Circle CI. A tool that will automatically run a test suite that we provide and provide those results to the reviewer. That way I don't need to run tests against contributors changes manually to evaluate if they are breaking or not.

Nice work on #34 though!

**Comment by lam2mo** [comment]
Closed by #37.
