### ISSUE TITLE
Merge and/or delete forloop branch

### ISSUE THREAD

**Issue by lam2mo** [JMU-CS/less-java#41]
Is the existence of this branch unnecessary because #3 is closed? Or should that issue be re-opened? The `forloop` is passing for me. I guess the main thing is that I want to make sure the branch has nothing pending for #29.

**Comment by Zamua** [comment]
This is probably safe to delete. Also not worth the merge time if it has anything valuable

**Comment by lam2mo** [comment]
Thanks--deleted.
