### ISSUE TITLE
Add else-if

### ISSUE THREAD

**Issue by lam2mo** [JMU-CS/less-java#81]
Maybe change grammar to:

`IF LP expr RP block (ELSE IF LP expr RP block)* (ELSE block)?`

And then de-sugar into nested conditional AST objects.

**Comment by lam2mo** [comment]
As we work on this, we should keep notes about which support files have to change when the grammar is changed, to see if there is any way to streamline future grammar changes.

**Comment by MrBartWolf** [comment]
After changing the g4 file to the grammar mentioned above and attempting to run the build again, parserASTMap.get(ctx.expr()) is still returning a single ASTNode, not the list that I need. It seemed like from our conversation that the parser would build itself to reflect the grammar in the file, but it doesn't seemed to have changed. Is there something else I should be doing to change the grammar?

**Comment by lam2mo** [comment]
That was my understanding as well. @Zamua do you have any insight here?

**Comment by Zamua** [comment]
Works fine for me. I added the grammer change, then I ran `gradle run` and got a nullpointer exception. I made it `ctx.expr().get(0)` on [this line](https://github.com/JMU-CS/less-java/blob/44cb540df44f29c1638c931e8853dde671c0fb1d/src/main/java/com/github/lessjava/visitor/impl/LJASTConverter.java#L327) and it compiled the compiler successfully. This change isn't correct, but it shows that `ctx.expr()` is a list now

**Comment by Zamua** [comment]
you can run the antlr task independently with `gradle generateGrammarSource`, but I don't think you have to do that. When you do `gradle run` it shows what tasks it's running in the progress bar, and that one shows up for me.

**Comment by MrBartWolf** [comment]
I found the problem, I was misunderstanding the relationship between ctx.expr() and parserASTMap.get(). Thanks for the help

**Comment by MrBartWolf** [comment]
The only files I needed to change to get this implemented were the grammer file itself and LJASTConverter.

**Comment by lam2mo** [comment]
Closed by #110
