### ISSUE TITLE
Reorder wrapper script output and add options

### ISSUE THREAD

**Issue by lam2mo** [JMU-CS/less-java#92]
The default behavior of `lj` should be "compile, test, run" (halting early if either compilation or testing fails). Options desired:

- only compile and test ("-t" or "-T"?)
- only compile and run ("-r" or "-R"?)

**Comment by MrBartWolf** [comment]
The option "-t" is already being used in the lj script to print all type changes found. I can either use a different option letter for the only compile and test function, or change the option to print the type changes. Otherwise, the options and reordering are ready.

**Comment by MrBartWolf** [comment]
@lam2mo @Zamua

**Comment by lam2mo** [comment]
I vote we change the type printing switch because it's only useful for compiler devs and it's ok to make it harder to turn on. Maybe make it "--types"?

**Comment by Zamua** [comment]
I think it would be confusing to have it as `--types`. You would expect that the long form `--types` would correspond with the short form `-t`. Maybe `--print-types`?

**Comment by lam2mo** [comment]
Closed by #101.
